CREATE TABLE books
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title               VARCHAR(255)                            NOT NULL,
    author              VARCHAR(255)                            NOT NULL,
    publish_date        date                                    NOT NULL,
    isbn                VARCHAR(255)                            NOT NULL,
    category            VARCHAR(255),
    availability_status BOOLEAN,
    CONSTRAINT pk_books PRIMARY KEY (id)
);

CREATE TABLE borrows
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    borrow_date TIMESTAMP WITHOUT TIME ZONE,
    return_date TIMESTAMP WITHOUT TIME ZONE,
    status      VARCHAR(255),
    books_id    BIGINT,
    CONSTRAINT pk_borrows PRIMARY KEY (id)
);

CREATE TABLE contribution
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    book_name         VARCHAR(255),
    author_name       VARCHAR(255),
    category          VARCHAR(255),
    language          VARCHAR(255),
    contributor_name  VARCHAR(255),
    contribution_date TIMESTAMP WITHOUT TIME ZONE,
    status            VARCHAR(255),
    CONSTRAINT pk_contribution PRIMARY KEY (id)
);

CREATE TABLE contribution_available_formats
(
    contribution_id   BIGINT NOT NULL,
    available_formats VARCHAR(255)
);

CREATE TABLE favorites
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT,
    book_id    BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_favorites PRIMARY KEY (id)
);

CREATE TABLE notes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT,
    book_id    BIGINT,
    content    TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_notes PRIMARY KEY (id)
);

CREATE TABLE password_reset_token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email       VARCHAR(255),
    token       VARCHAR(255),
    expiry_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_passwordresettoken PRIMARY KEY (id)
);

CREATE TABLE payment
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        BIGINT                                  NOT NULL,
    book_id        BIGINT                                  NOT NULL,
    amount         DECIMAL,
    payment_method VARCHAR(255),
    payment_status VARCHAR(255),
    transaction_id VARCHAR(255),
    currency       VARCHAR(255),
    payment_date   date,
    CONSTRAINT pk_payment PRIMARY KEY (id)
);

CREATE TABLE reviews
(
    review_id   BIGINT NOT NULL,
    user_id     BIGINT NOT NULL,
    book_id     BIGINT NOT NULL,
    rating      INTEGER,
    comment     VARCHAR(255),
    review_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_reviews PRIMARY KEY (review_id)
);




CREATE TABLE users
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reg_no               VARCHAR(255)                            NOT NULL,
    college_reg_no       VARCHAR(255)                            NOT NULL,
    email                VARCHAR(255)                            NOT NULL,
    password             VARCHAR(255)                            NOT NULL,
    name                 VARCHAR(255),
    role                 VARCHAR(255),
    is_verified          BOOLEAN,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    password_reset_token VARCHAR(255),
    token_expiry         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE books
    ADD CONSTRAINT uc_books_isbn UNIQUE (isbn);

ALTER TABLE users
    ADD CONSTRAINT uc_users_college_reg_no UNIQUE (college_reg_no);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_password_reset_token UNIQUE (password_reset_token);

ALTER TABLE users
    ADD CONSTRAINT uc_users_reg_no UNIQUE (reg_no);

ALTER TABLE borrows
    ADD CONSTRAINT FK_BORROWS_ON_BOOKS FOREIGN KEY (books_id) REFERENCES books (id);

ALTER TABLE borrows
    ADD CONSTRAINT FK_BORROWS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE favorites
    ADD CONSTRAINT FK_FAVORITES_ON_BOOK FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE favorites
    ADD CONSTRAINT FK_FAVORITES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE payment
    ADD CONSTRAINT FK_PAYMENT_ON_BOOK FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE payment
    ADD CONSTRAINT FK_PAYMENT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_BOOK FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE reviews
    ADD CONSTRAINT FK_REVIEWS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE contribution_available_formats
    ADD CONSTRAINT fk_contribution_availableformats_on_contribution FOREIGN KEY (contribution_id) REFERENCES contribution (id);