ALTER TABLE users
    ADD bio VARCHAR(500);

ALTER TABLE users
    ADD username VARCHAR(255);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE users
DROP
COLUMN name;

CREATE TABLE contact_message
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    email        VARCHAR(255),
    subject      VARCHAR(255),
    message      TEXT,
    submitted_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_contactmessage PRIMARY KEY (id)
);


ALTER TABLE payment
DROP CONSTRAINT fk_payment_on_book;

ALTER TABLE payment
DROP CONSTRAINT fk_payment_on_user;

ALTER TABLE reviews
DROP CONSTRAINT fk_reviews_on_book;

ALTER TABLE reviews
DROP CONSTRAINT fk_reviews_on_user;

ALTER TABLE user_password_reset_tokens
DROP CONSTRAINT fkinxw48vu6y9ovjiqhbtldx40l;

DROP TABLE payment CASCADE;

DROP TABLE reviews CASCADE;

ALTER TABLE user_password_reset_tokens
DROP COLUMN password_reset_tokens;

ALTER TABLE user_password_reset_tokens
DROP COLUMN user_id;