CREATE TABLE contact_message
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    email        VARCHAR(255),
    subject      VARCHAR(255),
    message      TEXT,
    submitted_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_contactmessage PRIMARY KEY (id)
);