ALTER TABLE users
    ADD bio VARCHAR(500);

ALTER TABLE users
    ADD username VARCHAR(255);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE users
DROP
COLUMN name;

CREATE TABLE contact_message
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    email        VARCHAR(255),
    subject      VARCHAR(255),
    message      TEXT,
    submitted_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_contactmessage PRIMARY KEY (id)
);