CREATE TABLE contact_message
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    email        VARCHAR(255),
    subject      VARCHAR(255),
    message      TEXT,
    submitted_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_contactmessage PRIMARY KEY (id)
);

ALTER TABLE books
    ADD available BOOLEAN;

ALTER TABLE books
    ADD book_url VARCHAR(255);

ALTER TABLE books
    ADD cover_url VARCHAR(255);

ALTER TABLE books
    ADD rating INTEGER;

ALTER TABLE books
DROP
COLUMN availability_status;

ALTER TABLE books
DROP
COLUMN image_url;